version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  userdb:
    container_name: userdb
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: userdb
    volumes:
      - ./data/userdb:/var/lib/mysql
      
  postdb:
    container_name:  postdb
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE:  postdb
    volumes:
      - ./data/postdb:/var/lib/mysql     
      
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
        
  mongodata: 
    container_name: mongodata # container name  
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    command: --break-mongo
    
  mongodb: 
    container_name: mongodb # container name
    image: mongo # specify image to build container from
    volumes_from:
     - mongodata
    ports:
      - "27017:27017" # specify port forewarding
    command: --smallfiles --rest --auth    
    